### ISSUE TITLE
Different Endpoints for Todo Tasks and done tasks

### ISSUE THREAD

**Issue by psud** [alha96/flatgame#3]
It makes sense to have an extra endpoint for done tasks since these are saved differently in the backend. Additionally,  a userImg should be sent with each done task

**Comment by good-live** [comment]
/task --> Normal tasks
/flat/:flatid/task --> Done tasks

There is already a userid sent with each done task?

**Comment by psud** [comment]
ok, thanks
Yes, the userIMAGE ist needed in addition to the ID. Since this is requested in #4 this issue is closed
